name: link_bridge
description: >
  A Flutter plugin for handling deep links on Android and iOS. 
  Supports both custom URL schemes and universal links for seamless cross-platform navigation.

version: 0.0.4

repository: https://github.com/YoussefShehab/LinkBridge
issue_tracker: https://github.com/YoussefShehab/LinkBridge/issues
homepage: https://github.com/YoussefShehab/LinkBridge

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.link_bridge.link_bridge
        pluginClass: LinkBridgePlugin
      ios:
        pluginClass: LinkBridgePlugin
