name: link_bridge
description: "Deep Link Flutter Plugin For Android, iOS."
version: 0.0.3
repository: https://github.com/YoussefShehab/LinkBridge
issue_tracker: https://github.com/YoussefShehab/LinkBridge/issues


environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  plugin:
    platforms:
      android:
        package: com.link_bridge.link_bridge
        pluginClass: LinkBridgePlugin
      ios:
        pluginClass: LinkBridgePlugin